INSERT INTO public."Games" (gameTitle, description, releaseDate, price, difficultyID) VALUES
('The Witcher 3: Wild Hunt', 'Open-world RPG where you play as Geralt of Rivia on a quest to find his adopted daughter.', '2015-05-19', 29.99, 3),
('Grand Theft Auto V', 'Action-adventure game set in the fictional state of San Andreas, featuring three playable protagonists.', '2013-09-17', 39.99, 3),
('Red Dead Redemption 2', 'Western-themed action-adventure game following outlaw Arthur Morgan and the Van der Linde gang.', '2018-10-26', 49.99, 3),
('The Legend of Zelda: Breath of the Wild', 'Open-world action-adventure game set in the fantasy land of Hyrule.', '2017-03-03', 59.99, 3),
('Dark Souls III', 'Challenging action RPG known for its tough difficulty and intricate level design.', '2016-04-12', 19.99, 3),
('Skyrim', 'Epic fantasy RPG set in the vast world of Tamriel, where you can explore dungeons, complete quests, and slay dragons.', '2011-11-11', 39.99, 3),
('Mass Effect 2', 'Sci-fi RPG where you lead a diverse team on a suicide mission to stop an ancient alien race.', '2010-01-26', 19.99, 2),
('Portal 2', 'First-person puzzle-platform game where you solve puzzles using a portal gun.', '2011-04-19', 9.99, 2),
('BioShock Infinite', 'First-person shooter set in the floating city of Columbia, known for its captivating story and unique setting.', '2013-03-26', 29.99, 2),
('Horizon Zero Dawn', 'Action RPG set in a post-apocalyptic world overrun by robotic creatures.', '2017-02-28', 39.99, 2),
('The Last of Us Part II', 'Action-adventure game set in a post-apocalyptic world filled with hostile humans and fungal creatures.', '2020-06-19', 49.99, 2),
('Uncharted 4: A Thief''s End', 'Action-adventure game following treasure hunter Nathan Drake on his final adventure.', '2016-05-10', 29.99, 2),
('God of War', 'Action-adventure game based on Norse mythology, where you play as Kratos on a quest with his son Atreus.', '2018-04-20', 39.99, 2),
('Persona 5', 'Japanese RPG where you play as a high school student who moonlights as a phantom thief.', '2017-09-15', 49.99, 2),
('Half-Life: Alyx', 'Virtual reality first-person shooter set in the Half-Life universe.', '2020-03-23', 59.99, 2),
('Minecraft', 'Sandbox game where players can build and explore blocky worlds.', '2011-11-18', 19.99, 1),
('Stardew Valley', 'Farming simulation game where you inherit a farm and can grow crops, raise animals, and build relationships.', '2016-02-26', 14.99, 1),
('Fall Guys: Ultimate Knockout', 'Online multiplayer party game where players compete in a series of mini-games to be the last one standing.', '2020-08-04', 19.99, 1),
('Rocket League', 'Vehicular soccer game where players control rocket-powered cars to score goals.', '2015-07-07', 19.99, 1),
('Overcooked! 2', 'Cooperative cooking simulation game where players prepare and serve dishes in various chaotic kitchens.', '2018-08-07', 24.99, 1),
('Civilization VI', 'Turn-based strategy game where players build and manage their own civilization throughout history.', '2016-10-21', 59.99, 1),
('Terraria', '2D sandbox game where players can explore, build, and fight in a procedurally generated world.', '2011-05-16', 9.99, 1),
('Cities: Skylines', 'City-building simulation game where players can create and manage their own cities.', '2015-03-10', 29.99, 1),
('Rainbow Six Siege', 'Tactical first-person shooter where teams of operators compete in various game modes.', '2015-12-01', 29.99, 1),
('Genshin Impact', 'Action RPG with gacha game mechanics set in the fantasy world of Teyvat.', '2020-09-28', 29.99, 1),
('Phasmophobia', 'Online multiplayer psychological horror game where players investigate haunted locations as ghost hunters.', '2020-09-18', 29.99, 1),
('Valheim', 'Survival game set in a procedurally generated world inspired by Norse mythology.', '2021-02-02', 29.99, 1),
('Hades', 'Roguelike action dungeon crawler where players fight their way out of the underworld.', '2020-09-17', 29.99, 1),
('Among Us', 'Online multiplayer party game where players work together to complete tasks on a spaceship while impostors try to sabotage them.', '2018-06-15', 29.99, 1),
('Phasmophobia', 'Online multiplayer psychological horror game where players investigate haunted locations as ghost hunters.', '2020-09-18', 29.99, 1),
('Valheim', 'Survival game set in a procedurally generated world inspired by Norse mythology.', '2021-02-02', 29.99, 1),
('Hades', 'Roguelike action dungeon crawler where players fight their way out of the underworld.', '2020-09-17', 29.99, 1),
('Stardew Valley', 'Farming simulation game where you inherit a farm and can grow crops, raise animals, and build relationships.', '2016-02-26', 29.99, 1),
('Minecraft', 'Sandbox game where players can build and explore blocky worlds.', '2011-11-18', 29.99, 1),
('Overcooked! 2', 'Cooperative cooking simulation game where players prepare and serve dishes in various chaotic kitchens.', '2018-08-07', 29.99, 1),
('Terraria', '2D sandbox game where players can explore, build, and fight in a procedurally generated world.', '2011-05-16', 29.99, 1),
('Civilization VI', 'Turn-based strategy game where players build and manage their own civilization throughout history.', '2016-10-21', 29.99, 1),
('Rainbow Six Siege', 'Tactical first-person shooter where teams of operators compete in various game modes.', '2015-12-01', 29.99, 1),
('Genshin Impact', 'Action RPG with gacha game mechanics set in the fantasy world of Teyvat.', '2020-09-28', 29.99, 1),
('Phasmophobia', 'Online multiplayer psychological horror game where players investigate haunted locations as ghost hunters.', '2020-09-18', 29.99, 1),
('Valheim', 'Survival game set in a procedurally generated world inspired by Norse mythology.', '2021-02-02', 29.99, 1),
('Hades', 'Roguelike action dungeon crawler where players fight their way out of the underworld.', '2020-09-17', 29.99, 1),
('Stardew Valley', 'Farming simulation game where you inherit a farm and can grow crops, raise animals, and build relationships.', '2016-02-26', 29.99, 1),
('Minecraft', 'Sandbox game where players can build and explore blocky worlds.', '2011-11-18', 29.99, 1),
('Overcooked! 2', 'Cooperative cooking simulation game where players prepare and serve dishes in various chaotic kitchens.', '2018-08-07', 29.99, 1),
('Terraria', '2D sandbox game where players can explore, build, and fight in a procedurally generated world.', '2011-05-16', 29.99, 1),
('Civilization VI', 'Turn-based strategy game where players build and manage their own civilization throughout history.', '2016-10-21', 29.99, 1),
('Rainbow Six Siege', 'Tactical first-person shooter where teams of operators compete in various game modes.', '2015-12-01', 29.99, 1),
('Genshin Impact', 'Action RPG with gacha game mechanics set in the fantasy world of Teyvat.', '2020-09-28', 29.99, 1),
('Phasmophobia', 'Online multiplayer psychological horror game where players investigate haunted locations as ghost hunters.', '2020-09-18', 29.99, 1),
('Valheim', 'Survival game set in a procedurally generated world inspired by Norse mythology.', '2021-02-02', 29.99, 1),
('Hades', 'Roguelike action dungeon crawler where players fight their way out of the underworld.', '2020-09-17', 29.99, 1),
('Stardew Valley', 'Farming simulation game where you inherit a farm and can grow crops, raise animals, and build relationships.', '2016-02-26', 29.99, 1),
('Minecraft', 'Sandbox game where players can build and explore blocky worlds.', '2011-11-18', 29.99, 1),
('Overcooked! 2', 'Cooperative cooking simulation game where players prepare and serve dishes in various chaotic kitchens.', '2018-08-07', 29.99, 1),
('Terraria', '2D sandbox game where players can explore, build, and fight in a procedurally generated world.', '2011-05-16', 29.99, 1),
('Civilization VI', 'Turn-based strategy game where players build and manage their own civilization throughout history.', '2016-10-21', 29.99, 1),
('Rainbow Six Siege', 'Tactical first-person shooter where teams of operators compete in various game modes.', '2015-12-01', 29.99, 1),
('Genshin Impact', 'Action RPG with gacha game mechanics set in the fantasy world of Teyvat.', '2020-09-28', 29.99, 1),
('Phasmophobia', 'Online multiplayer psychological horror game where players investigate haunted locations as ghost hunters.', '2020-09-18', 29.99, 1),
('Valheim', 'Survival game set in a procedurally generated world inspired by Norse mythology.', '2021-02-02', 29.99, 1),
('Hades', 'Roguelike action dungeon crawler where players fight their way out of the underworld.', '2020-09-17', 29.99, 1),
('Stardew Valley', 'Farming simulation game where you inherit a farm and can grow crops, raise animals, and build relationships.', '2016-02-26', 29.99, 1),
('Minecraft', 'Sandbox game where players can build and explore blocky worlds.', '2011-11-18', 29.99, 1),
('Overcooked! 2', 'Cooperative cooking simulation game where players prepare and serve dishes in various chaotic kitchens.', '2018-08-07', 29.99, 1),
('Terraria', '2D sandbox game where players can explore, build, and fight in a procedurally generated world.', '2011-05-16', 29.99, 1),
('Civilization VI', 'Turn-based strategy game where players build and manage their own civilization throughout history.', '2016-10-21', 29.99, 1),
('Rainbow Six Siege', 'Tactical first-person shooter where teams of operators compete in various game modes.', '2015-12-01', 29.99, 1),
('Genshin Impact', 'Action RPG with gacha game mechanics set in the fantasy world of Teyvat.', '2020-09-28', 29.99, 1),
('Phasmophobia', 'Online multiplayer psychological horror game where players investigate haunted locations as ghost hunters.', '2020-09-18', 29.99, 1),
('Valheim', 'Survival game set in a procedurally generated world inspired by Norse mythology.', '2021-02-02', 29.99, 1),
('Hades', 'Roguelike action dungeon crawler where players fight their way out of the underworld.', '2020-09-17', 29.99, 1);